Repository raspbernetes/k8s-cluster-installation, pull requests merged in 2021-03, with the labels that each got.

#113 Set hostname in common role
  ansible/roles/common/tasks/common.yml
Labels: size/XS

#116 add check to enable kube-proxy in init config
  ansible/roles/cluster/templates/kubeadm-config.yaml.j2
Labels: size/XS

#114 Replace pip installation with APT for python-openshift
  ansible/family_vars/archlinux.yml
  ansible/family_vars/debian.yml
  ansible/roles/common/tasks/archlinux.yml
  ansible/roles/common/tasks/debian.yml
Labels: size/S

#115 Feat/cleanup
  ansible/group_vars/all.yml
  ansible/group_vars/cluster.yml
  ansible/group_vars/masters.yml
  ansible/playbooks/nuke.yml
  ansible/roles/cloudflared/defaults/main.yml
  ansible/roles/kubernetes/defaults/main.yml
  ansible/roles/kubernetes/tasks/debian.yml
  ansible/roles/storage/defaults/main.yml
  ansible/roles/storage/tasks/main.yml
  ansible/roles/storage/tasks/pre_checks.yml
Labels: size/M

#120 Fixes for ansible-lint errors and warnings
  ansible/playbooks/nuke.yml
  ansible/roles/cluster/tasks/pre_checks.yml
  ansible/roles/cni/meta/main.yml
  ansible/roles/docker_cache/tasks/registry.yml
  ansible/roles/docker_cache/tasks/traefik.yml
Labels: size/M
